### ISSUE TITLE
[Suggestion] A button to turn Auto-HDR on/off 

### ISSUE THREAD

**Issue by JediRhymeTrix** [Codectory/HDR-Profile#14]
This would allow Auto-HDR based on running applications to be turned off while still allowing HDR to be toggled manually from the status page or tray icon.

**Comment by Codectory** [comment]
So you mean in the tray menu? I think I don't understand it completly.

**Comment by JediRhymeTrix** [comment]
I mean the option to turn off auto-hdr but still be able to manually toggle HDR using the usual manual toggle button in the app or in the tray menu.

**Comment by Codectory** [comment]
But this should work right now. Just set the HDR Mode to none.

Maybe, I should choose other wordings.

Vedant Vohra ***@***.***> schrieb am Fr. 19. März 2021 um
16:47:

**Comment by JediRhymeTrix** [comment]
Oh, yeah. My bad. Closing this. Thanks!
