### ISSUE TITLE
App fails to start

### ISSUE THREAD

**Issue by jackhulk** [Codectory/HDR-Profile#5]
Hello

Great looking app, just the thing I have been searching for, just one problem... nothing happens when I double click on HDRProfile.exe.
R
unning Window 10. Downloaded latest 1.5.3, tried both x86 and x64 versions, but it just won't start. Where am I going wrong please?

**Comment by jackhulk** [comment]
Tested 1.5.2 x64 which is working.

**Comment by Codectory** [comment]
Can you try 1.5.3 with admin rights?
HDRProfile initially creates settings file, so the root directory has to be
writable.

jackhulk <notifications@github.com> schrieb am Mo. 8. Feb. 2021 um 02:07:

**Comment by Codectory** [comment]
Can you check the newest release?

**Comment by jackhulk** [comment]
Thanks for the update, this opens perfectly. I ran in to some other issues however so had to turn the app off for now. My usage was very limited however (used with Red Dead Redemption 2), so may work perfectly well with other games.

Issues 1 - RDR2 would randomly crash due to HDR randomly being switch off, and sometimes back on again. I had HDR Profile >  HDR Mode set to 'Running' with RDR2 the only application added.

Issue 2 - HDR Profile sometimes switched HDR on randomly when not even running RDR2, and also experienced it interfering with other apps, none of which were included added in HDR Profile. Opera browser for example would cause screens to flick on and off several times before settling down and running as normal.

This was all with version 1.5.2, so will give the new 1.5.5 a try, thank you.

**Comment by Codectory** [comment]
Please, create others issues, they still exist. I cannot explain, why HDRProfile would ever activate HDR while running apps which haven't been added. The only possible would be, if all apps are named rdr2.exe, but I think that is not the case. I will close this now, as this issue seems to be fixed.
