### ISSUE TITLE
How to launch it ?

### ISSUE THREAD

**Issue by VincentDaviet** [Codectory/HDR-Profile#6]
Do we have to launch it via Source\Debug_x64\HDRProfile.exe with admin rights ?
It works like this, because I did not find other .exe files. 
Is is the right way ?

**Comment by Codectory** [comment]
Just download the release files:
https://github.com/Codectory/HDR-Profile/releases/tag/1.5.3 and start
HDRProfile.exe. You don’t need to start it with admin rights.
Just ask me again, if it’s not working this way.

VincentDaviet <notifications@github.com> schrieb am Fr. 12. Feb. 2021 um
16:23:

**Comment by VincentDaviet** [comment]
Hi, my question is : Is it normal tu launch HDRProfile.exe from Debug_x64 folder ?
I thought there should be the HDRProfile.exe file in Release_x64 folder, for example ?

**Comment by Codectory** [comment]
You need to download the exe files from the link above.

VincentDaviet <notifications@github.com> schrieb am So. 14. Feb. 2021 um
11:20:

**Comment by Codectory** [comment]
No, this link I send you in my first comment if this issue: https://github.com/Codectory/HDR-Profile/releases/tag/1.5.3

**Comment by VincentDaviet** [comment]
Ok sorry, I was downloading the source code. It's ok with the Release_HDRProfile_1-5-3_xXX.zip
